---
- hosts: web
  gather_facts: false  # Gather facts later when SSH user is known.
  pre_tasks:
    - name: Include shared variables.
      ansible.builtin.include_vars:
        file: input_shared.yaml
    - name: Include web-specific variables.
      ansible.builtin.include_vars:
        file: input_web.yaml
  roles:   # Order is important here.
    - common
    - certbot
    - web
...
