---
- hosts: web
  gather_facts: false
  pre_tasks:
    - name: Include shared variables.
      ansible.builtin.include_vars:
        file: input_shared.yaml
    - name: Include web-specific variables.
      ansible.builtin.include_vars:
        file: input_web.yaml
  roles:
    - common
    - certbot
    - web
...
