---
roles:
  - name: geerlingguy.nginx
    version: "3.0.0"

  - name: geerlingguy.mysql
    version: "3.3.0"

  - name: geerlingguy.php
    version: "4.6.0"

  - name: geerlingguy.nodejs
    version: "5.1.0"

  - name: geerlingguy.certbot
    version: "4.0.0"

collections:
  - name: community.general
    version: "3.0.0"
...
