---
roles:
  - name: geerlingguy.nginx
    version: "3.0.0"

  - name: geerlingguy.mysql
    version: "3.3.0"

  - name: geerlingguy.php
    version: "4.6.0"

  - name: geerlingguy.nodejs
    version: "5.1.0"

  - name: geerlingguy.certbot
    version: "4.1.0"

  - name: robertdebock.fail2ban
    version: "4.0.2"

collections:
  - name: community.general
    version: "3.0.0"

  - name: community.crypto
    version: "1.7.0"
...
