---
- hosts: wordpress
  gather_facts: false
  pre_tasks:
    - name: Include shared variables.
      ansible.builtin.include_vars:
        file: input_shared.yaml
    - name: Include WordPress-specific variables.
      ansible.builtin.include_vars:
        file: input_wordpress.yaml
  roles:
    - common
    - certbot
    - wordpress
...
