---
- hosts: wordpress
  gather_facts: false  # Gather facts later when SSH user is known.
  pre_tasks:
    - name: Include shared variables.
      ansible.builtin.include_vars:
        file: input_shared.yaml
    - name: Include WordPress-specific variables.
      ansible.builtin.include_vars:
        file: input_wordpress.yaml
  roles:  # Order is important here.
    - common
    - certbot
    - wordpress
...
