---
- name: Use new port specified in input for SSH connections.
  set_fact:
    ansible_port: "{{ new_ssh_port }}"

- name: Configure and start Certbot.
  remote_user: "{{ admin_username }}"
  when: start_certbot | bool
  become: true
  block:
    - name: Gather facts about host system.
      ansible.builtin.gather_facts: {}

    - name: Ensure there is an user for automatically renewing HTTPS certificate.
      ansible.builtin.user:
        name: certbot
        system: true
        shell: /bin/false
        create_home: false
        password_lock: true

    - name: Proceed with Certbot setup.
      include_role:
        name: geerlingguy.certbot
      vars:
        certbot_install_method: package
        certbot_auto_renew_user: certbot
        certbot_create_if_missing: true
        certbot_create_method: standalone
        certbot_admin_email: "{{ certbot_notifications_email }}"
        certbot_create_standalone_stop_services:
          - nginx
        certbot_certs:
          - domains: "{{ prefix_www_to_domain_name | ternary([domain_name, 'www.' + domain_name], [domain_name]) }}"
...
